import 'package:flutter/material.dart';
import 'package:storeapp/addshoesclass.dart';

List<Addshoesclass> menshoes = [
  Addshoesclass(
    name: "Mens Running Tennis Shoes Slip",
    description:
        "Comfortable Mesh Upper.The latest in mesh technology features an elastic design that intertwines with the knitted upper,without the feeling of binding,without stuffy and helping your foot feel secure,comfortable as you all day.",
    price: '38',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF)],
    image: 'https://m.media-amazon.com/images/I/61Iy1OzNrRL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Men's Slip on Walking Shoes",
    description:
        "Mesh,breathable and lightweight knitted upper.Memory foam insole.Low-top design and easy pull on and take off.",
    price: '26',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/61PxtGdjk1L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "PUMA Men's Roma Sneaker",
    description:
        "Retro-inspired sneaker featuring signature Formstrips at sides and T-toe overlay",
    price: '46',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/71r+Pgk8VXL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Feethit Mens Slip On Walking Shoes",
    description:
        "High Elastic Outsole: The modules of mens running shoes that make up the shoe's outsole are designed to offer shock absorption and stability to the feet at key points of impact.",
    price: '37',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFB71C1C)],
    image:
        'https://m.media-amazon.com/images/I/51WNCLQv2fL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Men's Swift Run Sneaker",
    description:
        "Lightweight EVA midsole; Enjoy the comfort and performance of OrthoLite sockliner",
    price: '57',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFF5F5F5), Color(0xFF9E7D2E)],
    image: 'https://m.media-amazon.com/images/I/71P9hMTgfDL._AC_SX575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "New Balance Men's 608 V5 Casual Comfort",
    description:
        "Leather upper ,ABZORB midsole cushioning aids in absorbing forceful impacts ,Premium PU comfort insert",
    price: '70',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF303030)],
    image:
        'https://m.media-amazon.com/images/I/61Ht6pj0JiL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "PUMA Mens Tazon 6 Cross Trainer",
    description:
        "CONTEMPORARY DESIGN: Seasonal fracture graphic on this Tazon Cross-Trainer for a modern look.",
    price: '60',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFB71C1C)],
    image:
        'https://m.media-amazon.com/images/I/51xqcM6XFAL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "COKAFIL Mens Running Shoes",
    description:
        "Fashion mesh upper design,keeps the feet dry and breathable, makes you fell comfortable while exercising",
    price: '46',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/71z5hTV3wDL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "SKDOIUL Sport Running Shoes",
    description:
        "The upper is mesh-designed, and the hole between the mesh fibers forms an air passage for excellent air permeability.",
    price: '40',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFF000000), Color(0xFF00008B)],
    image:
        'https://m.media-amazon.com/images/I/71UthjtR+7L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "SKDOIUL Men Sport Athletic Sneakers",
    description:
        "The interior of the shoe is designed with a honeycomb hole to absorb sweat and deodorize, allowing your feet to breathe freely.",
    price: '39',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFBC02D)],
    image: 'https://m.media-amazon.com/images/I/61nh3QuQ++L._AC_SY575_.jpg',
    isfavorite: false,
  ),
];

List<Addshoesclass> womenshoes = [
  Addshoesclass(
    name: "Nike Women's Low-Top Sneakers",
    description:
        "You are looking for a spark, something that gives you extra momentum or reignites your routine with a little vigor. Create incentives for your feet with the Nike Initiator Air. Mesh on the upper helps your feet breathe while you give it all.",
    price: '30',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF)],
    image: 'https://m.media-amazon.com/images/I/71VSKsjdOzL._AC_SX575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "MEHOTO Women's Tennis Sneakers",
    description:
        "The running shoes use air cushion design, provide cushioning and support effect for the feet",
    price: '35',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [
      Color(0xFFFFFFFF),
      Color(0xFF000000),
      Color.fromARGB(255, 248, 90, 79),
    ],
    image:
        'https://m.media-amazon.com/images/I/71HbJeSpJRL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Under Armor Women's Charged Sneaker",
    description:
        "Engineered mesh upper is extremely lightweight & breathable, with strategic support where you need it. Foam padding placed around your ankle collar & under the tongue for an incredibly comfortable fit & feel.",
    price: '40',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/51PgLKADR9L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Nike Women's Low-Top Sneakers",
    description:
        "The upper and synthetic strati overlaps that add textures, depth and breathability. The embroidered details combine with dynamic overlaps for a fascinating and original style.",
    price: '37',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFDD5A00)],
    image:
        'https://m.media-amazon.com/images/I/516uK2ZxwPL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Sam Edelman Women's Langley Sneakers",
    description: "Sam Edelman Womens Langley Lace Up Sneaker",
    price: '28',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [
      Color(0xFFFFFFFF),
      Color(0xFF000000),
      Color(0xFFDD5A00),
      Color(0xFFF9A825),
    ],
    image:
        'https://m.media-amazon.com/images/I/51cjSy3dLZL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Women's Pure Sneakers",
    description:
        "adidas womens Cloudfoam Pure , Women's streamlined shoes for all-day comfort , FLEXIBLE UPPER: Soft textile upper is stretchy and comfortable .",
    price: '55',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF303030)],
    image:
        'https://m.media-amazon.com/images/I/51LkHWropaL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "GUESS Women's Loven Sneakers",
    description:
        "This lace up look features GUESS logo hardware on the side with the hottest fashion colors of the season mixed and matched. This shoe is comfy, cool and ready to knock your socks off.",
    price: '44',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFFF9A825)],
    image:
        'https://m.media-amazon.com/images/I/518G3jarbOL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Women's Kaptir Flow Sneakers",
    description:
        "These women's adidas shoes are perfectly proportioned and ultra-comfy. They're great for active days when you still want a stylish edge.",
    price: '65',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [
      Color(0xFFFFFFFF),
      Color(0xFFF06292),
      Color.fromARGB(255, 248, 90, 79),
    ],
    image:
        'https://m.media-amazon.com/images/I/51kaLY7gM+L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Skechers Women's Summits Sneakers",
    description: "Skechers Women's Summits",
    price: '43',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF1E88E5)],
    image:
        'https://m.media-amazon.com/images/I/61mgslY9j7L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "TSIODFO Women's Sneakers",
    description:
        "Comfortable and breathable fabric , Non-slip Wear-resistant outsole , Slip on design easy to wear, fashion colour with everything .",
    price: '39',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF6A1B9A)],
    image: 'https://m.media-amazon.com/images/I/61ZUB-Ux9IL._AC_SY575_.jpg',
    isfavorite: false,
  ),
];

List<Addshoesclass> kidsshoes = [
  Addshoesclass(
    name: "Boys Girls Lightweight Tennis Sneakers",
    description:
        "Toddler boys girls slip on sneakers combine flexible and hard wearing. Girls' running shoes with non-slip outsole guarantees firm grip on various surfaces and make safety for your child, helping to prevent slips and falls.",
    price: '14',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF)],
    image:
        'https://m.media-amazon.com/images/I/61ZNoNE6DIL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Santiro Boys Shoes Girls Kids Sneakers ",
    description:
        "High Elastic MD Outsole, soft , Anti-slip, wearable and shock absorption.Knitted Mesh Upper offers comfort and air permeability; Keep your child away from foot smelly.",
    price: '35',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFF4527A0)],
    image: 'https://m.media-amazon.com/images/I/71wHD1p3tsL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "DREAM PAIRS High Top Sneaker",
    description:
        "These kids’ high-top sneakers feature a firm heel counter to support their basketball adventures and everyday activities.",
    price: '36',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFF8BBD0)],
    image: 'https://m.media-amazon.com/images/I/71GvD8rLpNL._AC_SY695_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Boys Girls Sneakers for Kids Non-Slip Tennis",
    description:
        "Knitted Mesh Upper Offers Comfort And Air Permeability; Make Your Foot Always Keeps Dry And Cool.",
    price: '34',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFF000000), Color(0xFFFDD835)],
    image:
        'https://m.media-amazon.com/images/I/81na9hJBwOL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "PUMA Unisex-Child Club 5v5 Sneaker",
    description:
        "ENHANCED TECHNOLOGY: Utilizes PUMA's SoftFoam+, a step-in comfort sockliner designed to provide soft cushioning thanks to its extra thick heel.",
    price: '55',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFF48FB1), Color(0xFF9575CD), Color(0xFF9E7D2E)],
    image:
        'https://m.media-amazon.com/images/I/51PucLcUHrL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Kids' Lite Racer Adapt 7.0 Sneaker",
    description:
        "EASY ON AND OFF: Slip-on construction with decorative elastic laces makes getting them dressed simple",
    price: '30',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF303030)],
    image:
        'https://m.media-amazon.com/images/I/71GPpyzxuaL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "koppu Kids Shoes Running Shoes ",
    description:
        "Knitted Mesh Upper offers comfort and air permeability; Keep your child away from foot smelly",
    price: '34',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFF737373)],
    image:
        'https://m.media-amazon.com/images/I/71zHEabsuAL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Skechers Boys' Microspec II - Vovrix",
    description: "Skechers Boys' Microspec II - Vovrix",
    price: '30',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFB71C1C)],
    image: 'https://m.media-amazon.com/images/I/71tAh7qqLkL._AC_SX575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Skechers Kids' MICROSPEC II - ZOVRIX",
    description: "Mesh and synthetic upper with stretch laces",
    price: '30',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [
      Color(0xFFFFFFFF),
      Color(0xFF000000),
      Color(0xFF4527A0),
      Color(0xFF81C784),
    ],
    image:
        'https://m.media-amazon.com/images/I/81PIfXNQl9L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "RUNSIDE Boys Girls Sneakers",
    description:
        "Breathable Upper: Let your little one's feet breathe easy with our superfine knit upper toddler sneakers that have excellent airflow and quick-drying capabilities",
    price: '22',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF6A1B9A)],
    image:
        'https://m.media-amazon.com/images/I/81bNLMo793L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
];

List<Addshoesclass> newbornshoes = [
  Addshoesclass(
    name: "MORENDL Toddler Slip On Sneakers",
    description:
        "Adjustable Upper Width: The adjustable upper design provides a customizable fit, ensuring maximum comfort for your baby growing feet.",
    price: '23',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF)],
    image:
        'https://m.media-amazon.com/images/I/611CAaWUb3L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "MORENDL Baby Shoes Walking Sock Shoes",
    description:
        "Breathable: These toddler walking sock shoes keep baby feet cool and comfortable during daily activities with excellent breathability.",
    price: '22',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFCDD2)],
    image: 'https://m.media-amazon.com/images/I/71Kc+EtXo-L._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Clowora Unsex Baby Shoes ",
    description: "soft sole and breathable material.",
    price: '18',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFF9E7D2E)],
    image: 'https://m.media-amazon.com/images/I/61uH70HjaaL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Unisex Baby Girls Boys Shoes",
    description:
        "Safety Tested for Peace Of Mind, No Any Stimulation to The Skin of Baby.",
    price: '10',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFD32F2F)],
    image:
        'https://m.media-amazon.com/images/I/61XZZ55-PmL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Gerber Baby Newborn Infant",
    description:
        "Pair our baby and toddler shoes with our Onesies bodysuits, baby and toddler outfits and sets, shorts, & accessories. Perfect to give as a thoughtful baby shower or birthday gift.",
    price: '12',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFF3E0)],
    image: 'https://m.media-amazon.com/images/I/917-jDOtIQL._AC_SY695_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Meckior Toddler Baby Boys Girls",
    description:
        "Soft,Comfort,Breathable, Have Flexible Laces,Lightweight insole and Anti-Slip Cotton Sole is Good for Baby’s Feet Feel The Ground Naturally,Perfect for Learning Walk.Available for 0-18 Months Baby",
    price: '12',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFF000000)],
    image: 'https://m.media-amazon.com/images/I/61eTeSChogL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Unisex Baby Soft Sole Sneakers",
    description:
        "Soft and Comfortable: Crafted with soft canvas and denim uppers, ensuring a snug and cozy fit for tiny feet.",
    price: '10',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFF06292)],
    image: 'https://m.media-amazon.com/images/I/81BOSyskaaL._AC_SY695_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Baby Boys&Girls Shoes Baby Walking Shoes",
    description:
        "This baby shoes has removable memory foam insoles provide children with a comfortable and soft wearing experience and are easy to clean.",
    price: '20',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFF737373)],
    image: 'https://m.media-amazon.com/images/I/71kqZeZGqnL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Eashi Baby Boy Girl Non-Skid Indoor Infant",
    description:
        "Soft Rubber Sole & High Top Grip: Soft rubber bottom are comfrotable, extra high top grip provide excellent ankle support, avoid sliding slipping, a perfect baby first walking shoes.",
    price: '15',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/71iOxht+khL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "FEETCITY Baby Shoes Boys Girls First Walking",
    description:
        "Rubber Sole & High Top Grip：Rubber traction sole and extra high grip provide excellent ankle support, avoid sliding slipping, a perfect baby first walking shoes.",
    price: '19',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFF48FB1), Color(0xFF6A1B9A)],
    image:
        'https://m.media-amazon.com/images/I/71hJPyVtlVL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
];

List<Addshoesclass> allshoes = [
  Addshoesclass(
    name: "Mens Running Tennis Shoes Slip",
    description:
        "Comfortable Mesh Upper.The latest in mesh technology features an elastic design that intertwines with the knitted upper,without the feeling of binding,without stuffy and helping your foot feel secure,comfortable as you all day.",
    price: '38',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF)],
    image: 'https://m.media-amazon.com/images/I/61Iy1OzNrRL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Men's Slip on Walking Shoes",
    description:
        "Mesh,breathable and lightweight knitted upper.Memory foam insole.Low-top design and easy pull on and take off.",
    price: '26',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/61PxtGdjk1L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "PUMA Men's Roma Sneaker",
    description:
        "Retro-inspired sneaker featuring signature Formstrips at sides and T-toe overlay",
    price: '46',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/71r+Pgk8VXL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Feethit Mens Slip On Walking Shoes",
    description:
        "High Elastic Outsole: The modules of mens running shoes that make up the shoe's outsole are designed to offer shock absorption and stability to the feet at key points of impact.",
    price: '37',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFB71C1C)],
    image:
        'https://m.media-amazon.com/images/I/51WNCLQv2fL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Men's Swift Run Sneaker",
    description:
        "Lightweight EVA midsole; Enjoy the comfort and performance of OrthoLite sockliner",
    price: '57',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFF5F5F5), Color(0xFF9E7D2E)],
    image: 'https://m.media-amazon.com/images/I/71P9hMTgfDL._AC_SX575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "New Balance Men's 608 V5 Casual Comfort",
    description:
        "Leather upper ,ABZORB midsole cushioning aids in absorbing forceful impacts ,Premium PU comfort insert",
    price: '70',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF303030)],
    image:
        'https://m.media-amazon.com/images/I/61Ht6pj0JiL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "PUMA Mens Tazon 6 Cross Trainer",
    description:
        "CONTEMPORARY DESIGN: Seasonal fracture graphic on this Tazon Cross-Trainer for a modern look.",
    price: '60',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFB71C1C)],
    image:
        'https://m.media-amazon.com/images/I/51xqcM6XFAL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "COKAFIL Mens Running Shoes",
    description:
        "Fashion mesh upper design,keeps the feet dry and breathable, makes you fell comfortable while exercising",
    price: '46',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/71z5hTV3wDL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "SKDOIUL Sport Running Shoes",
    description:
        "The upper is mesh-designed, and the hole between the mesh fibers forms an air passage for excellent air permeability.",
    price: '40',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFF000000), Color(0xFF00008B)],
    image:
        'https://m.media-amazon.com/images/I/71UthjtR+7L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "SKDOIUL Men Sport Athletic Sneakers",
    description:
        "The interior of the shoe is designed with a honeycomb hole to absorb sweat and deodorize, allowing your feet to breathe freely.",
    price: '39',
    category: 'men',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFBC02D)],
    image: 'https://m.media-amazon.com/images/I/61nh3QuQ++L._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Nike Women's Low-Top Sneakers",
    description:
        "You are looking for a spark, something that gives you extra momentum or reignites your routine with a little vigor. Create incentives for your feet with the Nike Initiator Air. Mesh on the upper helps your feet breathe while you give it all.",
    price: '30',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF)],
    image: 'https://m.media-amazon.com/images/I/71VSKsjdOzL._AC_SX575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "MEHOTO Women's Tennis Sneakers",
    description:
        "The running shoes use air cushion design, provide cushioning and support effect for the feet",
    price: '35',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [
      Color(0xFFFFFFFF),
      Color(0xFF000000),
      Color.fromARGB(255, 248, 90, 79),
    ],
    image:
        'https://m.media-amazon.com/images/I/71HbJeSpJRL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Under Armor Women's Charged Sneaker",
    description:
        "Engineered mesh upper is extremely lightweight & breathable, with strategic support where you need it. Foam padding placed around your ankle collar & under the tongue for an incredibly comfortable fit & feel.",
    price: '40',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/51PgLKADR9L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Nike Women's Low-Top Sneakers",
    description:
        "The upper and synthetic strati overlaps that add textures, depth and breathability. The embroidered details combine with dynamic overlaps for a fascinating and original style.",
    price: '37',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFDD5A00)],
    image:
        'https://m.media-amazon.com/images/I/516uK2ZxwPL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Sam Edelman Women's Langley Sneakers",
    description: "Sam Edelman Womens Langley Lace Up Sneaker",
    price: '28',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [
      Color(0xFFFFFFFF),
      Color(0xFF000000),
      Color(0xFFDD5A00),
      Color(0xFFF9A825),
    ],
    image:
        'https://m.media-amazon.com/images/I/51cjSy3dLZL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Women's Pure Sneakers",
    description:
        "adidas womens Cloudfoam Pure , Women's streamlined shoes for all-day comfort , FLEXIBLE UPPER: Soft textile upper is stretchy and comfortable .",
    price: '55',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF303030)],
    image:
        'https://m.media-amazon.com/images/I/51LkHWropaL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "GUESS Women's Loven Sneakers",
    description:
        "This lace up look features GUESS logo hardware on the side with the hottest fashion colors of the season mixed and matched. This shoe is comfy, cool and ready to knock your socks off.",
    price: '44',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFFF9A825)],
    image:
        'https://m.media-amazon.com/images/I/518G3jarbOL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Women's Kaptir Flow Sneakers",
    description:
        "These women's adidas shoes are perfectly proportioned and ultra-comfy. They're great for active days when you still want a stylish edge.",
    price: '65',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [
      Color(0xFFFFFFFF),
      Color(0xFFF06292),
      Color.fromARGB(255, 248, 90, 79),
    ],
    image:
        'https://m.media-amazon.com/images/I/51kaLY7gM+L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Skechers Women's Summits Sneakers",
    description: "Skechers Women's Summits",
    price: '43',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF1E88E5)],
    image:
        'https://m.media-amazon.com/images/I/61mgslY9j7L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "TSIODFO Women's Sneakers",
    description:
        "Comfortable and breathable fabric , Non-slip Wear-resistant outsole , Slip on design easy to wear, fashion colour with everything .",
    price: '39',
    category: 'women',
    size: [
      'US 5 (Adult Small)',
      'US 6 (Adult Small)',
      'US 7 (Adult Small)',
      'US 8 (Adult Medium)',
      'US 9 (Adult Medium)',
      'US 10 (Adult Medium)',
      'US 11 (Adult Medium)',
      'US 12 (Adult Large)',
      'US 13 (Adult Large)',
      'US 14 (Adult Large)',
      'US 15 (Adult X-Large)',
      'US 16 (Adult X-Large)',
      'US 17 (Adult X-Large)',
      'US 18 (Adult X-Large)',
      'US 19 (Adult X-Large)',
      'US 20 (Adult X-Large)',
    ],

    colors: [Color(0xFFFFFFFF), Color(0xFF6A1B9A)],
    image: 'https://m.media-amazon.com/images/I/61ZUB-Ux9IL._AC_SY575_.jpg',
    isfavorite: false,
  ),

  Addshoesclass(
    name: "Boys Girls Lightweight Tennis Sneakers",
    description:
        "Toddler boys girls slip on sneakers combine flexible and hard wearing. Girls' running shoes with non-slip outsole guarantees firm grip on various surfaces and make safety for your child, helping to prevent slips and falls.",
    price: '14',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF)],
    image:
        'https://m.media-amazon.com/images/I/61ZNoNE6DIL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Santiro Boys Shoes Girls Kids Sneakers ",
    description:
        "High Elastic MD Outsole, soft , Anti-slip, wearable and shock absorption.Knitted Mesh Upper offers comfort and air permeability; Keep your child away from foot smelly.",
    price: '35',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFF4527A0)],
    image: 'https://m.media-amazon.com/images/I/71wHD1p3tsL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "DREAM PAIRS High Top Sneaker",
    description:
        "These kids’ high-top sneakers feature a firm heel counter to support their basketball adventures and everyday activities.",
    price: '36',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFF8BBD0)],
    image: 'https://m.media-amazon.com/images/I/71GvD8rLpNL._AC_SY695_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Boys Girls Sneakers for Kids Non-Slip Tennis",
    description:
        "Knitted Mesh Upper Offers Comfort And Air Permeability; Make Your Foot Always Keeps Dry And Cool.",
    price: '34',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFF000000), Color(0xFFFDD835)],
    image:
        'https://m.media-amazon.com/images/I/81na9hJBwOL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "PUMA Unisex-Child Club 5v5 Sneaker",
    description:
        "ENHANCED TECHNOLOGY: Utilizes PUMA's SoftFoam+, a step-in comfort sockliner designed to provide soft cushioning thanks to its extra thick heel.",
    price: '55',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFF48FB1), Color(0xFF9575CD), Color(0xFF9E7D2E)],
    image:
        'https://m.media-amazon.com/images/I/51PucLcUHrL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "adidas Kids' Lite Racer Adapt 7.0 Sneaker",
    description:
        "EASY ON AND OFF: Slip-on construction with decorative elastic laces makes getting them dressed simple",
    price: '30',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFF303030)],
    image:
        'https://m.media-amazon.com/images/I/71GPpyzxuaL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "koppu Kids Shoes Running Shoes ",
    description:
        "Knitted Mesh Upper offers comfort and air permeability; Keep your child away from foot smelly",
    price: '34',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFF737373)],
    image:
        'https://m.media-amazon.com/images/I/71zHEabsuAL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Skechers Boys' Microspec II - Vovrix",
    description: "Skechers Boys' Microspec II - Vovrix",
    price: '30',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFB71C1C)],
    image: 'https://m.media-amazon.com/images/I/71tAh7qqLkL._AC_SX575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Skechers Kids' MICROSPEC II - ZOVRIX",
    description: "Mesh and synthetic upper with stretch laces",
    price: '30',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [
      Color(0xFFFFFFFF),
      Color(0xFF000000),
      Color(0xFF4527A0),
      Color(0xFF81C784),
    ],
    image:
        'https://m.media-amazon.com/images/I/81PIfXNQl9L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "RUNSIDE Boys Girls Sneakers",
    description:
        "Breathable Upper: Let your little one's feet breathe easy with our superfine knit upper toddler sneakers that have excellent airflow and quick-drying capabilities",
    price: '22',
    category: 'kids',
    size: [
      '1-4 years (Toddler)',
      '4-7 years (Little Kid)',
      '7-12 years (Big Kid)',
      'US 1 (Big Kid)',
      'US 2 (Big Kid)',
      'US 3 (Big Kid)',
      'US 4 (Big Kid)',
      'US 5 (Big Kid)',
      'US 6 (Big Kid)',
      'US 7 (Big Kid)',
      'US 8 (Big Kid)',
      'US 9 (Big Kid)',
      'US 10 (Big Kid)',
      'US 11 (Big Kid)',
      'US 12 (Big Kid)',
      'US 13 (Big Kid)',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF6A1B9A)],
    image:
        'https://m.media-amazon.com/images/I/81bNLMo793L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),

  Addshoesclass(
    name: "MORENDL Toddler Slip On Sneakers",
    description:
        "Adjustable Upper Width: The adjustable upper design provides a customizable fit, ensuring maximum comfort for your baby growing feet.",
    price: '23',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF)],
    image:
        'https://m.media-amazon.com/images/I/611CAaWUb3L._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "MORENDL Baby Shoes Walking Sock Shoes",
    description:
        "Breathable: These toddler walking sock shoes keep baby feet cool and comfortable during daily activities with excellent breathability.",
    price: '22',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFCDD2)],
    image: 'https://m.media-amazon.com/images/I/71Kc+EtXo-L._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Clowora Unsex Baby Shoes ",
    description: "soft sole and breathable material.",
    price: '18',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFF9E7D2E)],
    image: 'https://m.media-amazon.com/images/I/61uH70HjaaL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Unisex Baby Girls Boys Shoes",
    description:
        "Safety Tested for Peace Of Mind, No Any Stimulation to The Skin of Baby.",
    price: '10',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFD32F2F)],
    image:
        'https://m.media-amazon.com/images/I/61XZZ55-PmL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Gerber Baby Newborn Infant",
    description:
        "Pair our baby and toddler shoes with our Onesies bodysuits, baby and toddler outfits and sets, shorts, & accessories. Perfect to give as a thoughtful baby shower or birthday gift.",
    price: '12',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFF3E0)],
    image: 'https://m.media-amazon.com/images/I/917-jDOtIQL._AC_SY695_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Meckior Toddler Baby Boys Girls",
    description:
        "Soft,Comfort,Breathable, Have Flexible Laces,Lightweight insole and Anti-Slip Cotton Sole is Good for Baby’s Feet Feel The Ground Naturally,Perfect for Learning Walk.Available for 0-18 Months Baby",
    price: '12',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFF000000)],
    image: 'https://m.media-amazon.com/images/I/61eTeSChogL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Unisex Baby Soft Sole Sneakers",
    description:
        "Soft and Comfortable: Crafted with soft canvas and denim uppers, ensuring a snug and cozy fit for tiny feet.",
    price: '10',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000), Color(0xFFF06292)],
    image: 'https://m.media-amazon.com/images/I/81BOSyskaaL._AC_SY695_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Baby Boys&Girls Shoes Baby Walking Shoes",
    description:
        "This baby shoes has removable memory foam insoles provide children with a comfortable and soft wearing experience and are easy to clean.",
    price: '20',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFF737373)],
    image: 'https://m.media-amazon.com/images/I/71kqZeZGqnL._AC_SY575_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "Eashi Baby Boy Girl Non-Skid Indoor Infant",
    description:
        "Soft Rubber Sole & High Top Grip: Soft rubber bottom are comfrotable, extra high top grip provide excellent ankle support, avoid sliding slipping, a perfect baby first walking shoes.",
    price: '15',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFFFFFFF), Color(0xFF000000)],
    image:
        'https://m.media-amazon.com/images/I/71iOxht+khL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
  Addshoesclass(
    name: "FEETCITY Baby Shoes Boys Girls First Walking",
    description:
        "Rubber Sole & High Top Grip：Rubber traction sole and extra high grip provide excellent ankle support, avoid sliding slipping, a perfect baby first walking shoes.",
    price: '19',
    category: 'newborn',
    size: [
      '0-3 months',
      '3-6 months',
      '6-9 months',
      '9-12 months',
      '12-18 months',
      '18-24 months',
    ],
    colors: [Color(0xFFF48FB1), Color(0xFF6A1B9A)],
    image:
        'https://m.media-amazon.com/images/I/71hJPyVtlVL._AC_UL480_FMwebp_QL65_.jpg',
    isfavorite: false,
  ),
];
